Feature/emily-daniel-catsuperhero modal
TritonSE/FIX-Landing-Page pull request #37
Opened 2023-04-23 19:40 UTC by EmilyMarschallNiswonger

### Tracking Info

Resolves #<issue number>

Make sure your branch name conforms to: `<feature|staging|bugfix|...>/<username>/<3-4 word description separated by dashes>`. Otherwise, please rename your branch and create a new PR.

### Changes

What changes did you make?

- TODO

### Testing

How did you confirm your changes worked?

- TODO

### Confirmation of Change

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

TODO...

2023-04-30 19:37 UTC, jacobayu submitted a review, later dismissed
Hello, really nice work, it looks so good. Just a few things I noticed

1. I noticed that if you close the modal by clicking out of it (not pressing the X), to re-open the it you have to double click the cloud to open it again. You probably have to flip open again like you did on line 101.

2. The buttons for the resource links on the modal don't change color when you hover over them. 

3. Last thing, for smaller screen sizes, the buttons at the bottom get pushed out when there is a lot of text (screenshot below

 
<img width="407" alt="Screen Shot 2023-04-30 at 12 35 30 PM" src="https://user-images.githubusercontent.com/57156703/235372930-8084efe2-aca4-44eb-a998-f8f3deb67fcd.png">

2023-04-30 19:39 UTC, jacobayu commented on src/lib/modal.svelte
> +              open = !open;
I think we have to flip open when the user clicks out of the modal as well instead of using the X

2023-05-09 20:41 UTC, EdwardLinS requested changes, later dismissed
Hi, I think this modal looks fantastic! However, I am encountering the same problem that Jacob is finding which are needing to click twice when the user clicks outside the modal to close it and some of the navigation buttons being pushed out on smaller screen sizes, specifically on step 5 and 6. Other than that, this look great! Nice work.

2023-05-10 22:59 UTC, Cubified approved these changes
LGTM 🚢 

Made some responsiveness fixes, everything else is from running the linter and merging with upstream.

2023-05-12 19:54 UTC, jacobayu approved these changes
still unsure if the buttons are supposed to change buttons on hover, but other than that LGTM!

2023-05-15 23:36 UTC, merged